swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/account/{accountId}:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Gets an account by ID
      description: API for fetching an account
      parameters:
        - name: accountId
          in: path
          description: Account ID
          type: integer
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Account data retrieved successfully
          schema:
            $ref: '#/definitions/AccountResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not found
        '500':
          description: Internal Server Error
  /user/account/{accountId}/transaction/{transactionId}/note:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Add note
      description: API to add a note on a transaction
      parameters:
        - name: accountId
          in: path
          description: Account ID
          type: integer
          required: true
        - name: transactionId
          in: path
          description: Transaction ID
          type: integer
          required: true
        - in: body
          name: body
          description: Note Payload
          required: true
          schema:
            $ref: '#/definitions/Note'
      produces:
        - application/json
      responses:
        '201':
          description: Note has been successfully added
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not found
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Edit note
      description: API to edit the note on a transaction
      parameters:
        - name: accountId
          in: path
          description: Account ID
          type: integer
          required: true
        - name: transactionId
          in: path
          description: Account ID
          type: integer
          required: true
        - in: body
          name: body
          description: Note Payload
          required: true
          schema:
            $ref: '#/definitions/Note'
      produces:
        - application/json
      responses:
        '204':
          description: Note has been successfully edited
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not found
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Delete note
      description: API to delete the note on a transaction
      parameters:
        - name: accountId
          in: path
          description: Account ID
          type: integer
          required: true
        - name: transactionId
          in: path
          description: Account ID
          type: integer
          required: true
      produces:
        - application/json
      responses:
        '204':
          description: Note has been successfully deleted
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not found
        '500':
          description: Internal Server Error
  /user/account/{accountId}/transaction/{transactionId}/category:
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Modify category
      description: API to modify category on a transaction
      parameters:
        - name: accountId
          in: path
          description: Account ID
          type: integer
          required: true
        - name: transactionId
          in: path
          description: Transaction ID
          type: integer
          required: true
        - in: body
          name: body
          description: Note Payload
          required: true
          schema:
            $ref: '#/definitions/Category'
      produces:
        - application/json
      responses:
        '204':
          description: Category has been successfully modifed
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not found
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  AccountResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          transactionId:
            type: object
            properties:
              name:
                type: string
              amount:
                type: integer
              transactionType:
                type: string
              category:
                type: string
              note:
                type: string
  Note:
    type: object
    properties:
      note:
        type: string
  Category:
    type: object
    properties:
      category:
        type: string